apiVersion: v1
kind: Service
metadata:
  namespace: vmall
  name: nginx
  labels:
    app: nginx
    tier: vmall
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
  selector:
    app: nginx
    tier: vmall
status:
  loadBalancer: {}
