apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: vmall
  name: php-fpm-pvc
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi