apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterrole
  namespace: {{ .Release.Name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Name }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io