apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Name }}
  name: mysql-pvc
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi