apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  labels:
    app: php-fpm
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    app: php-fpm
    tier: vmall
status:
  loadBalancer: {}

